'documentation 📃':
  - '\b(docs?|documentations?|specs?|specifications?|readme|manual|guide|tutorial)\b'

'ci 🏗️':
  - '\b(ci|ci[-/]cd|ci[-/]cds?|continuous\s+integration|continuous\s+delivery|continuous\s+deployment|pipeline|pipelines)\b'