'documentation 📃':
  - '(?i)\b(docs?|documentations?|specs?|specifications?|readme|manual|guide|tutorial)\b'

'ci 🏗️':
  - '(?i)\b(ci|ci[-/]cd|ci[-/]cds?|continuous\s+integration|continuous\s+delivery|continuous\s+deployment|pipeline|pipelines)\b'

'release ↗️':
  - '(?i)\b(release|releases?)\b'

'rejected ❌':
  - '(?i)\b(rejected|rejected\s+issue|rejected\s+pull\s+request)\b'

'question ✋':
  - '(?i)\b(question|questions?|need\s+help|need\s+help|doubts?)\b'

'vulnerability 🚨':
  - '(?i)\b(vulnerability|vulnerabilities?|security\s+alert)\b'

'dependabot 🤖':
  - '(?i)\b(dependabot|dependabot\s+alert)\b'

'enhancement 🔝':
  - '(?i)\b(enhancement|enhancements?|improvement|improvements?)\b'

'evolvability ♻️':
  - '(?i)\b(evolvability|evolvability\s+issue|evolvability\s+pull\s+request|refactoring|refactorings?|clean\s+code|clean\s+codes?)\b'

