name: Sync labels

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode without making changes"
        required: false
        type: boolean
        default: false

jobs:
  sync-labels:
    uses: ./.github/workflows/reusable-label-sync.yml
    with:
      labels_config_path: ".github/labeling/labels.yml"
      delete_other_labels: true
      dry_run: ${{ inputs.dry_run || false }}
        