name: Project automations

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  project-automations:
    uses: ./.github/workflows/reusable-project-automations.yml
    with:
      organization: ${{ vars.ORGANIZATION_NAME }}
      project_id: ${{ vars.GH_PROJECT_ID }}
    secrets:
      gh_project_token: ${{ secrets.GH_PROJECT_TOKEN }}


