name: "Reusable: Sync Labels"

on:
  workflow_call:
    inputs:
      labels_config_path:
        description: "Path to the labels configuration file"
        required: false
        type: string
        default: "https://raw.githubusercontent.com/guardiafinance/project-automations/refs/heads/main/.github/labeling/labels.yml"
      delete_other_labels:
        description: "Whether to delete labels not defined in config"
        required: false
        type: boolean
        default: true
      dry_run:
        description: "Run in dry-run mode without making changes"
        required: false
        type: boolean
        default: false
    secrets:
      token:
        description: "GitHub token or PAT"
        required: false

permissions:
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: "Sync Repository Labels"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: ${{ inputs.labels_config_path }}
          delete-other-labels: ${{ inputs.delete_other_labels }}
          dry-run: ${{ inputs.dry_run }}
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }} 